Repository NaughtyChas/Wordweeper, pull requests merged in 2024-11, with the labels that each got.

#4 [E1G-3] Add basic code scaffold for menu
  .idea/.gitignore
  .idea/ThePuzzleGame.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  main.py
  menu.py
Labels: content

#6 Update repository README
  .idea/workspace.xml
  README.md
Labels: documentation

#5 [E1G-4] Add board display / controlling logic
  .gitignore
  board.py
  diffcalc.py
  menu.py
  words.txt
Labels: content

#11 [E1G-6] Add terminal size check before printing the main screen
  board.py
  menu.py
Labels: bug

#18 [E1G-8] Bug fixes
  board.py
  menu.py
Labels: bug, enhancement

#19 [E1G-9] User system / Statistics system Implementation
  board.py
  data/user.txt
  menu.py
  user.py
  user_statistics.py
Labels: enhancement, content

#20 [E1G-10] Project restructuring
  .gitignore
  .idea/.gitignore
  .idea/ThePuzzleGame.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  data/words.txt
  game/classicEasy.py
  menu.py
  util/diffcalc.py
  util/user.py
  util/user_statistics.py
Labels: content

#17 [E1G-7] Scoring system rework
  game/classicEasy.py
Labels: scoring

#23 [E1G-13] Fix edge cases for mine hints
  game/classicEasy.py
  game/classicExpert.py
  game/classicHard.py
Labels: bug

#22 [E1G-12] Add comments / docstrings
  game/classicEasy.py
  game/classicExpert.py
  game/classicHard.py
  main.py
  menu.py
  util/diffcalc.py
  util/user.py
  util/user_statistics.py
Labels: documentation
